apps/commercefacile_web/lib/commercefacile_web/router.ex
defmodule Commercefacile.Web.Router do
  use Commercefacile.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :uploader do
    plug :fetch_session
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Commercefacile.Web do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/", PageController, :index

    scope "/auth" do
      get "/enregistrer", AuthController, :get_register
      post "/enregistrer", AuthController, :post_register
      get "/numero", AuthController, :get_verify
      post "/numero", AuthController, :post_verify
      get "/code", AuthController, :get_code
      post "/code", AuthController, :post_code
      get "/connecter", AuthController, :get_login
      post "/connecter", AuthController, :post_login
      get "/réinitialiser", AuthController, :get_reset
      post "/réinitialiser", AuthController, :post_reset
      get "/mot-de-passe", AuthController, :get_reset_verify
      get "/nouveau-numero", AuthController, :get_new_verify
      post "/se-deconnecter", AuthController, :logout
    end

    get "/annonces", AdController, :index
    get "/annonces/créer", AdController, :create
    post "/annonces", AdController, :save #not yet tested
    post "/annonces/private", AdController, :private_save #not yet tested
    get "/annonces/:uuid", AdController, :show
    get "/annonces/:uuid/modifier", AdController, :edit
    delete "/annonces/:uuid", AdController, :delete
    put "/annonces/:uuid", AdController, :update
    post "/annonces/:uuid/favorite", AdController, :favorite
    post "/annonces/:uuid/unfavorite", AdController, :unfavorite
    post "/annonces/:uuid/report", AdController, :report
    post "/annonces/:uuid/unreport", AdController, :unreport
    

    get "/help", InfoPageController, :help
    get "/about", InfoPageController, :about
    get "/terms", InfoPageController, :terms
    get "/privacy", InfoPageController, :privacy
    get "/contact", InfoPageController, :contact

    scope "/uploads" do
      post "/", UploadController, :upload
      delete "/:reference", UploadController, :delete
    end

    scope "/:phone" do
      get "/", UserController, :dashboard
      get "/boutique", UserController, :shop
      get "/favoris", UserController, :favorites
      get "/paramètres", UserController, :settings
      put "/paramètres/info", UserController, :update_info
      put "/paramètres/password", UserController, :change_password
    end
    
  end

  # Other scopes may use custom stacks.
  scope "/api/mobile", Commercefacile.Web.Api.Mobile do
    pipe_through :api

    scope "/auth" do
      post "/register", AuthenticationController, :register
      post "/login", AuthenticationController, :login
      post "/code", AuthenticationController, :code
      post "/phone", AuthenticationController, :phone
      post "/reset", AuthenticationController, :reset
    end

    scope "/ads" do
      get "/", AdController, :list
      post "/", AdController, :create
      get "/:uuid", AdController, :show
      put "/:uuid", AdController, :update
      delete "/:uuid", AdController, :delete
    end 

    scope "/account" do
      get "/ads", AccountController, :ads
      put "/", AccountController, :information
      put "/password", AccountController, :password
    end

    scope "/upload" do
      post "/", UploadController, :upload
      delete "/", UploadController, :remove
    end

    get "/categories", MiscellaneousController, :categories
    get "/locations", MiscellaneousController, :locations

    get "/:phone/shop", AccountController, :shop
  end
end

apps/commercefacile_web/lib/commercefacile_web/controllers/ad_controller.ex
defmodule Commercefacile.Web.AdController do
    use Commercefacile.Web, :controller

    alias Commercefacile.Web.Serializers.AdController, as: Serializer

    plug Guardian.Plug.EnsureAuthenticated, [handler: Commercefacile.Web.ErrorController]
    when action in [:private_save, :edit, :update, :delete]

    @ad_conditions [[key: "new", value: "Nouveau"], [key: "used", value: "Utilisé"]]
    @ad_images_session_key :ad_images

    def index(conn, params) do
        %{result: ads, pagination: paginate} = 
            Commercefacile.Ads.list(Map.merge(params, %{"status" => :online}))
        ads = Serializer.Index.Ad.to_map(ads)
        conn = add_fixtures(conn, :list)
        conn = assign(conn, :ads, ads)
        conn = assign(conn, :paginate, paginate)
        render conn, "index.html"
    end

    def create(conn, _params) do
        conn = case Guardian.Plug.current_resource(conn) do
            nil -> 
                assign(conn, :post_action, ad_path(conn, :save))
                |> assign(:changeset, Commercefacile.Ads.Ad.form_changeset(:guest))
            %Commercefacile.Accounts.User{} = user -> 
                change_type = if Commercefacile.Accounts.user_location_set?(user), do: :private, else: :private_with_location
                assign(conn, :post_action, ad_path(conn, :private_save))
                |> assign(:changeset, Commercefacile.Ads.Ad.form_changeset(change_type))
        end

        get_ad_images(conn)
        |> add_fixtures(:select)
        |> assign(:edit_mode, false)
        |> assign(:post_method, :post)
        |> render("create.html")
    end

    def save(conn, %{"ad" => %{"phone" => phone} = ad}) do
        # make sure of no invalid data
        images = get_session(conn, @ad_images_session_key) || []
        ad = Map.merge(ad, %{"images" => images})
        changeset = Commercefacile.Ads.Ad.form_changeset(ad, :guest)
        if changeset.valid? do
            conn = put_session(conn, :guest, Commercefacile.Accounts.new_guest(ad))
            # check phone is taken
            case Commercefacile.Accounts.phone_taken?(phone) do
                false -> 
                    {:ok, user, %{reference:  reference}} = Commercefacile.Accounts.new_user(ad)
                    put_session(conn, :user_in_register_mode, user)
                    |> put_session(:code_reference, reference)
                    |> redirect(to: auth_path(conn, :get_code))
                {true, :unverified_user, phone} -> 
                    put_flash(conn, :info, "Verify your phone to countinue")
                    |> put_session(:unverified_phone, phone)
                    |> redirect(to: auth_path(conn, :get_verify))
                {true, :inactive_user} -> 
                    put_status(conn, 400)
                    |> put_flash(:info, "Phone belongs to inactive account, contact adminst.. or new account")
                    |> assign(:post_action, :save)
                    |> assign(:post_method, :post)
                    |> assign(:edit_mode, false)
                    |> assign(:changeset, changeset)
                    |> render("create.html")
                {true, :active_user} -> 
                    put_session(conn, :login_phone, phone)
                    |> redirect(to: auth_path(conn, :get_login))
            end
        else
            IO.inspect changeset
            put_status(conn, 400)
            |> get_ad_images
            |> assign(:changeset, %{changeset | action: :validate})
            |> assign(:post_action, :save)
            |> assign(:post_method, :post)
            |> assign(:edit_mode, false)
            |> add_fixtures(:select)
            |> render("create.html")
        end
    end

    def private_save(conn, %{"ad" => ad} = _params) do
        user = Guardian.Plug.current_resource(conn)
        # IO.inspect params
        images = get_session(conn, @ad_images_session_key) || []
        ad = Map.merge(ad, %{"images" => images})
        # IO.inspect ad
        case Commercefacile.Ads.new_ad(ad, user) do
            {:ok, _} -> 
                conn
                |> redirect(to: user_path(conn, :dashboard, user.phone))
            {:error, :invalid_data, changeset} ->
                conn
                |> put_status(400)
                |> assign(:changeset, %{changeset | action: :validate})
                |> add_fixtures(:select)
                |> render("create.html")
            {:error, :internal_error} ->
                conn
                |> put_status(500)
                |> put_view(Commercefacile.Web.ErrorView)
                |> render("500.html")
            {:error, changeset} ->
                conn
                |> put_status(400)
                |> assign(:changeset, changeset)
                |> add_fixtures(:select)
                |> render("create.html")
        end
    end

    def show(conn, %{"uuid" => uuid}) do
        user = Guardian.Plug.current_resource(conn)
        case Commercefacile.Ads.get_ad(uuid: uuid, status: :online) do
            {:error, :not_found} -> 
                put_status(conn, :not_found)
                |> put_view(Commercefacile.Web.ErrorView)
                |> render("404.html")
            {:ok, ad, author} -> 
                assign(conn, :ad, Serializer.Show.Ad.to_map(ad, scope: user))
                |> assign(:author, Serializer.Show.Author.to_map(author))
                |> render("show.html")
        end
    end

    def edit(conn, %{"uuid" => uuid}) do
        user = Guardian.Plug.current_resource(conn)
        case Commercefacile.Ads.get_ad(uuid: uuid, user: user) do
            {:error, :not_found} -> 
                put_status(conn, :not_found)
                |> put_view(Commercefacile.Web.ErrorView)
                |> render("404.html")
            {:ok, ad} -> 
                %{uuid: uuid, rejecteds: {fields, locales}, images: images} = ad = Serializer.Edit.Ad.to_map(ad)

                assign(conn, :changeset, Commercefacile.Ads.Ad.form_changeset(ad, :private))
                |> add_fixtures(:select)
                |> assign(:rejecteds, locales || [])
                |> assign(:rejected_fields, fields || [])
                |> assign(:edit_mode, true)
                |> assign(:post_action, ad_path(conn, :update, uuid))
                |> assign(:post_method, :put)
                |> put_ad_images(images)
                |> render("create.html")
        end
    end

    def update(conn, %{"uuid" => uuid, "ad" => ad}) do
        user = Guardian.Plug.current_resource(conn)
        # sync images
        images = get_session(conn, @ad_images_session_key) || []
        ad = Map.merge(ad, %{"images" => images})
        
        case Commercefacile.Ads.edit_ad(uuid, ad, user) do
            {:error, :invalid_data, changeset} ->
                IO.inspect {:invalid_data, changeset}
                conn
                |> put_status(400)
                |> get_ad_images
                |> assign(:changeset, %{changeset | action: :validate})
                |> add_fixtures(:select)
                |> assign(:edit_mode, true)
                |> assign(:post_action, ad_path(conn, :update, uuid))
                |> assign(:post_method, :put)
                |> render("create.html")
            {:error, changeset} ->
                IO.inspect {:error, changeset}
                conn
                |> put_status(400)
                |> get_ad_images
                |> assign(:changeset, changeset)
                |> assign(:edit_mode, true)
                |> assign(:post_action, ad_path(conn, :update, uuid))
                |> assign(:post_method, :put)
                |> add_fixtures(:select)
                |> render("create.html")
            {:ok, _} -> 
                redirect(conn, to: user_path(conn, :dashboard, user.phone))
        end
    end

    def favorite(conn, %{"uuid" => uuid}) do
        
    end

    def unfavorite(conn, %{"uuid" => uuid}) do
        
    end

    def report(conn, %{"uuid" => uuid}) do
        
    end

    def unreport(conn, %{"uuid" => uuid}) do
        
    end

    def delete(conn, %{"uuid" => uuid}) do
        user = Guardian.Plug.current_resource(conn)
        case Commercefacile.Ads.delete_ad(uuid: uuid, user: user) do
            {:error, :not_found} -> 
                put_status(conn, :not_found)
                |> put_view(Commercefacile.Web.ErrorView)
                |> render("404.html")
            {:ok, _} -> 
                redirect(conn, to: user_path(conn, :dashboard, user.phone))
        end
    end

    defp add_fixtures(conn, :select) do
        categories = Commercefacile.Ads.get_categories(:main_with_children)
            |> Serializer.Create.Categories.to_list(:select)
            # get locations
        locations = Commercefacile.Locations.get_regions(:togo, :with_cities)
            |> Serializer.Create.Locations.to_list(:select)

        assign(conn, :locations, locations)
        |> assign(:categories, categories)
        |> assign(:conditions, @ad_conditions)
    end
    defp add_fixtures(conn, :list) do
        # get categories
        categories = Commercefacile.Ads.get_categories(:main_with_children)
            |> Serializer.Index.Categories.to_map
        # get locations
        locations = Commercefacile.Locations.get_regions(:togo, :with_cities)
            |> Serializer.Index.Locations.to_map
        assign(conn, :locations, locations)
        |> assign(:categories, categories)
    end

    defp get_ad_images(conn) do
        case get_session(conn, @ad_images_session_key) do
            nil -> 
                IO.inspect("Session Images is empty")
                assign(conn, :images, [])
            old when is_list(old) ->
                conn = assign(conn, :images, old)
                IO.inspect(get_session(conn, @ad_images_session_key))
                conn
        end
    end

    defp put_ad_images(conn, images) do
        assign(conn, :images, images)
        |> put_session(@ad_images_session_key, images)

apps/commercefacile_web/lib/commercefacile_web/controllers/api/mobile/ad_controller.ex
defmodule Commercefacile.Web.Api.Mobile.AdController do
    use Commercefacile.Web, :controller

    def list(conn, _params) do
        
    end

    def show(conn, _params) do
        
    end

    def create(conn, _params) do
        
    end

    def update(conn, _params) do
        
    end

    def delete(conn, _params) do
        
    end
end

apps/commercefacile_web/lib/commercefacile_web/views/ad_view.ex
defmodule Commercefacile.Web.AdView do
    use Commercefacile.Web, :view

    def render("title.create.html", _assings) do
        ~E(<title>Commercefacile.com | Deposer une annonce</title>)
    end

    def render("title.index.html", _assings) do
        ~E(<title>Commercefacile.com | Toutes annonces</title>)
    end

    def render("title.show.html", %{ad: ad}) do
        ~E(<title>Commercefacile.com | <%= ad.title %></title>)
    end

    def render("title.edit.html", %{ad: ad}) do
        ~E(<title>Commercefacile.com | Modifier <%= ad.title %></title>)
    end

    def render("meta.show.html", %{conn: conn, ad: %{uuid: uuid, title: title, description: description, pictures: [%{path: first}|_], }}) do
        description = Curtail.truncate(description, length: 300)
        url = ad_url(conn, :show, uuid)
        ~E"""
        <meta itemprop="name"               content="Commercefacile.com | <%= title %>">
        <meta itemprop="description"        content="<%= description %>">
        <meta itemprop="image"              content="<%= first %>">

        <meta property="og:url"             content="<%= url %>">
        <meta property="og:type"            content="website" />
        <meta property="og:title"           content="Commercefacile.com | <%= title %>" />
        <meta property="og:description"     content="<%= description %>" />
        <meta property="og:image"           content="<%= first %>">
        
        <meta name="twitter:card"           content="summary_large_image">
        <meta name="twitter:url"            content="<%= url %>">
        <meta name="twitter:site"           content="@commercefacile">
        <meta name="twitter:creator"        content="Commercefacile.com">
        <meta name="twitter:title"          content="Commercefacile.com | <%= title %>">
        <meta name="twitter:description"    content="<%= description %>">
        <meta name="twitter:image"          content="<%= first %>">
        """
    end

    def rejected?(%{assigns: assigns}, field) do
        unless assigns["edit_mode"] do
            ""
        else
            if field in assigns["rejected_fields"] do
                " rejected "
            else
                ""
            end
        end
    end
end

apps/commercefacile_web/lib/commercefacile_web/templates/ad/_categories_dropdown_menu_item.html.eex
<optgroup label="<%= @ad.name %>">
    <%= render_many @ad.subs, Commercefacile.Web.AdView, "_categories_dropdown_menu_sub_item.html", assigns %>    
</optgroup>

apps/commercefacile_web/lib/commercefacile_web/templates/ad/_categories_dropdown_menu_sub_item.html.eex
<option value="<%= @ad.uuid %>"><%= @ad.name %></option>

apps/commercefacile_web/lib/commercefacile_web/templates/ad/_categories_mega_menu.html.eex
<% [first_categories | [second_categories | [third_categories | [fourth_categories]]]] = Enum.chunk(@categories, 3, 3, []) %>
<div class="columns">
    <div class="column is-3">
        <aside style="margin-bottom: 5px;" class="menu">
            <ul class="menu-list">
                <li><a onclick="selectCategory({name: 'Toutes Categories', uuid: null})" class="is-active">Toutes Categories</a></li>
            </ul>
        </aside>
        <%= render_many(first_categories, Commercefacile.Web.AdView, "_categories_mega_menu_item.html", assigns) %>
    </div>
    <div class="column is-3">
        <%= render_many(second_categories, Commercefacile.Web.AdView, "_categories_mega_menu_item.html", assigns) %>
    </div>
    <div class="column is-3">
        <%= render_many(third_categories, Commercefacile.Web.AdView, "_categories_mega_menu_item.html", assigns) %>
    </div>
    <div class="column is-3">
        <%= render_many(fourth_categories, Commercefacile.Web.AdView, "_categories_mega_menu_item.html", assigns) %>
    </div>
</div>

apps/commercefacile_web/lib/commercefacile_web/templates/ad/_categories_mega_menu_sub_item.html.eex
<% name = String.replace(@ad.name, "'", "\\'") %>
<li><a onclick="selectCategory({name: '<%= name %>', uuid: '<%= raw @ad.uuid %>'})"><%= @ad.name %></a></li>

apps/commercefacile_web/lib/commercefacile_web/templates/ad/ad_image.html.eex
<div class="field is-horizontal">
    <div class="field-label">
        <input type="text" hidden name="images[<%= @url %>]">
    </div>
    <div class="field-body">
        <div class="column is-12">
            <div class="box" style="padding: .25rem; border-radius: 3px; position: relative;">
                <a style="position: absolute; top: -5px; right: -5px;" class="delete is-danger"></a>
                <article class="media">
                    <div class="media-left">
                        <div class="ad-image-preview-wrapper">
                            <img src="<%= @url %>">
                        </div>
                    </div>
                    <div class="media-content">
                        <nav class="level is-mobile">
                            <progress style="border-radius: 3px;" class="progress is-success is-small" value="100" max="100"></progress>
                        </nav>
                    </div>
                </article>
            </div>
        </div>
    </div>
</div>

apps/commercefacile_web/lib/commercefacile_web/templates/ad/scripts.create.html.eex
<script>
    window.totalOfImagesInSession = <%= length(@images) %>;
    window.sessionImages = <%= raw Poison.encode! @images %>;
    window.uploadUrl = "<%= upload_path(@conn, :upload) %>";
    window.csrfToken = <%= raw Plug.CSRFProtection.get_csrf_token() |> Poison.encode! %>;
    window.editMode = <%= @edit_mode %>

    function openCategoryMegaMenu(){
        document.querySelector(".category-mega-menu").classList.toggle("is-hidden");
    }

    function selectCategory(category){
        document.querySelector(".select.category span").innerText = category.name;
        document.querySelector("input[name='c']").value = category.uuid;
        document.querySelector(".category-mega-menu").classList.toggle("is-hidden");
    }

    // document.querySelector(".select.category").addEventListener("click", function(){
        
    // })
</script>
<script type="text/x-template" id="imagePreviewTemplate">
    <div class="field is-horizontal">
        <div class="field-label">
            <input type="text" hidden :name="inputValue">
        </div>
        <div class="field-body">
            <div class="column is-12">
                <div class="box" style="padding: .25rem; border-radius: 3px; position: relative;">
                    <a v-if="showDelete" @click="remove" class="delete"></a>
                    <article class="media">
                        <div class="media-left">
                            <div class="ad-image-preview-wrapper">
                                <img v-if="inProgress || success" :src="thumbnail">
                                <a style="border: none; background: transparent;" @click="retry" v-if="failed" class="button is-small">
                                    <span class="icon is-large">
                                        <i style="color: #77829d;" class="fa fa-refresh"></i>
                                    </span>
                                </a>
                            </div>
                        </div>
                        <div class="media-content" style="height: 64px; display: flex; flex-direction: column; justify-content: center;">
                            <progress style="border-radius: 3px;" :class="['progress', 'is-small', progressClass]" :value="progressPercentage" max="100">15%</progress>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>
</script>
<script type="text/x-template" id="sessionImageTemplate">
    <div class="field is-horizontal">
        <div class="field-label">
            <input type="text" hidden :name="inputValue">
        </div>
        <div class="field-body">
            <div class="column is-12">
                <div class="box" style="padding: .25rem; border-radius: 3px; position: relative;">
                    <a @click="remove" class="delete"></a>
                    <article class="media">
                        <div class="media-left">
                            <div class="ad-image-preview-wrapper">
                                <img :src="imageUrl">
                            </div>
                        </div>
                        <div class="media-content" style="height: 64px; display: flex; flex-direction: column; justify-content: center;">
                            <progress style="border-radius: 3px;" class="progress is-small is-success" value="100" max="100"></progress>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intro.js/2.5.0/intro.min.js"></script>
<script src="<%= static_path(@conn, "/js/create.js") %>"></script>
<script>
    function createCookie(name,value,days) {
        if (days) {
            var date = new Date();
            date.setTime(date.getTime()+(days*24*60*60*1000));
            var expires = "; expires="+date.toGMTString();
        }
        else var expires = "";
        document.cookie = name+"="+value+expires+"; path=/";
    }

    function readCookie(name) {
        var nameEQ = name + "=";
        var ca = document.cookie.split(';');
        for(var i=0;i < ca.length;i++) {
            var c = ca[i];
            while (c.charAt(0)==' ') c = c.substring(1,c.length);
            if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
        }
        return null;
    }

    function eraseCookie(name) {
        createCookie(name,"",-1);
    }

    var introOptions = {
        'nextLabel': 'suivant',
        'prevLabel': 'précédent',
        'doneLabel': 'terminé',
        'skipLabel': 'laisser tomber',
        'overlayOpacity': '0.5',
        'showStepNumbers': false,
        'showBullets': false,
        'scrollToElement': true,
        'exitOnOverlayClick': false,
        'hidePrev': true,
        'hideNext': true
    };
    var introObj = introJs().setOptions(introOptions);
    introObj.onexit(function(){
        console.log("cookies exit");
        createCookie("already", true);
    });
    introObj.oncomplete(function(){
        console.log("cookies done");
        createCookie("already", true);
    });

    var already = readCookie("already");
    if(!already){
        eraseCookie("already");
        introObj.start();
    }
    console.log("cookies", already);

    var showHelpButton = document.querySelector('.show-help');
    showHelpButton.addEventListener('click', function(){
        introObj.start();
    });
</script>

apps/commercefacile_web/lib/commercefacile_web/templates/ad/scripts.index.html.eex
<script src="<%= static_path(@conn, "/js/vendors/blazy.min.js") %>"></script>
<script>
    ;(function() {
        var bLazy = new Blazy({offset: 20});
    })();
    function getJsonFromUrl() {
        var query = location.search.substr(1);
        var result = {};
        query.split("&").forEach(function(part) {
            var item = part.split("=");
            result[item[0]] = decodeURIComponent(item[1]);
        });
        return result;
    }
    function updateQueryStringParam (key, value) {
        var baseUrl = [location.protocol, '//', location.host, location.pathname].join(''),
            urlQueryString = document.location.search,
            newParam = key + '=' + value,
            params = '?' + newParam;
        // If the "search" string exists, then build params from it
        if (urlQueryString) {
            updateRegex = new RegExp('([\?&])' + key + '[^&]*');
            removeRegex = new RegExp('([\?&])' + key + '=[^&;]+[&;]?');
            if( typeof value == 'undefined' || value == null || value == '' ) { // Remove param if value is empty
                params = urlQueryString.replace(removeRegex, "$1");
                params = params.replace( /[&;]$/, "" );
            } else if (urlQueryString.match(updateRegex) !== null) { // If param exists already, update it
                params = urlQueryString.replace(updateRegex, "$1" + newParam);
            } else { // Otherwise, add it to end of query string
                params = urlQueryString + '&' + newParam;
            }
        }
        window.history.replaceState({}, "", baseUrl + params);
    };

    function addslashes(str) {
        return (str + '').replace(/[\\"']/g, '\\$&').replace(/\u0000/g, '\\0');
    }

    function selectCategory(category){
        document.querySelector(".select.category span").innerText = category.name;
        document.querySelector("input[name='c']").value = category.uuid;
        document.querySelector(".category-mega-menu").classList.toggle("is-hidden");
    }

    document.querySelector(".select.category").addEventListener("click", function(){
        document.querySelector(".category-mega-menu").classList.toggle("is-hidden");
    })

    if(getJsonFromUrl().hasOwnProperty("q")){
        var searchInputs = document.querySelectorAll("input[name='q']");
        var query = getJsonFromUrl().q;
        console.log(searchInputs);
        searchInputs.forEach(function(input){
            input.value = query.replace("+", " ");
        });
    }

    var filterInput = document.querySelector("select.filter");

    if(getJsonFromUrl().hasOwnProperty("s")){
        var filter = getJsonFromUrl().s;
        if(filter.startsWith("p")){
            if(filter.split("|")[1] === "asc"){
                filterInput.selectedIndex = 2;
            }else{
                filterInput.selectedIndex = 3;
            }
        }else{
            if(filter.split("|")[1] === "asc"){
                filterInput.selectedIndex = 1;
            }else{
                filterInput.selectedIndex = 0;
            }
        }
    }

    filterInput.addEventListener("change", function(e){
        var url = document.location.href,
            filter = e.target.value;
            if(document.location.search){
                console.log("has query");
                if(getJsonFromUrl().hasOwnProperty("s")){
                    // update it to new value
                    console.log("has s");
                    updateQueryStringParam("s", filter);
                    window.location.reload(true);
                }else{
                    // add it
                    var new_url = url + "&s=" + filter;
                    return document.location = new_url;
                }
            }else{
                // add query string
                var new_url = url + "?s=" + filter;
                document.location = new_url;
            }
    })
</script>

apps/commercefacile_web/lib/commercefacile_web/templates/ad/styles.show.html.eex
<link rel="stylesheet" href="<%= static_path(@conn, "/css/vendors/tiny-slider.css") %>">
<style type="text/css">
    *{
        color: #33446d;
    }
    a, span.price{
        color: #f9b462;
        transition: all .3s;
    }
    a:hover{
        text-decoration: underline;
        color: #33446d;
    }
    a.user{
        font-weight: bold;
    }
    .ad-image-wrapper, .ad-thumbnails-image-wrapper{
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: whitesmoke;
    }
    .ad-image-wrapper {
        height: 25rem !important;
    }
    .ad-image-wrapper img, .ad-thumbnails-image-wrapper img {
        max-width: 100% !important;
        max-height: 100% !important;
        display: block !important;
        margin: 0 auto !important;
    }
    .thumbnails{
        display: flex;
        justify-content: space-around;
        margin-top: 5px;
    }
    .ad-thumbnails-image-wrapper{
        width: 96px;
        height: 96px;
    }

    table.table{
        border-top: 1px solid #dbdbdb;
    }

    strong{
        color: #33446d;
    }
</style>