apps/commercefacile_web/lib/commercefacile_web/router.ex
defmodule Commercefacile.Web.Router do
  use Commercefacile.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :uploader do
    plug :fetch_session
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Commercefacile.Web do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/", PageController, :index

    scope "/auth" do
      get "/enregistrer", AuthController, :get_register
      post "/enregistrer", AuthController, :post_register
      get "/numero", AuthController, :get_verify
      post "/numero", AuthController, :post_verify
      get "/code", AuthController, :get_code
      post "/code", AuthController, :post_code
      get "/connecter", AuthController, :get_login
      post "/connecter", AuthController, :post_login
      get "/réinitialiser", AuthController, :get_reset
      post "/réinitialiser", AuthController, :post_reset
      get "/mot-de-passe", AuthController, :get_reset_verify
      get "/nouveau-numero", AuthController, :get_new_verify
      post "/se-deconnecter", AuthController, :logout
    end

    get "/annonces", AdController, :index
    get "/annonces/créer", AdController, :create
    post "/annonces", AdController, :save #not yet tested
    post "/annonces/private", AdController, :private_save #not yet tested
    get "/annonces/:uuid", AdController, :show
    get "/annonces/:uuid/modifier", AdController, :edit
    delete "/annonces/:uuid", AdController, :delete
    put "/annonces/:uuid", AdController, :update
    post "/annonces/:uuid/favorite", AdController, :favorite
    post "/annonces/:uuid/unfavorite", AdController, :unfavorite
    post "/annonces/:uuid/report", AdController, :report
    post "/annonces/:uuid/unreport", AdController, :unreport
    

    get "/help", InfoPageController, :help
    get "/about", InfoPageController, :about
    get "/terms", InfoPageController, :terms
    get "/privacy", InfoPageController, :privacy
    get "/contact", InfoPageController, :contact

    scope "/uploads" do
      post "/", UploadController, :upload
      delete "/:reference", UploadController, :delete
    end

    scope "/:phone" do
      get "/", UserController, :dashboard
      get "/boutique", UserController, :shop
      get "/favoris", UserController, :favorites
      get "/paramètres", UserController, :settings
      put "/paramètres/info", UserController, :update_info
      put "/paramètres/password", UserController, :change_password
    end
    
  end

  # Other scopes may use custom stacks.
  scope "/api/mobile", Commercefacile.Web.Api.Mobile do
    pipe_through :api

    scope "/auth" do
      post "/register", AuthenticationController, :register
      post "/login", AuthenticationController, :login
      post "/code", AuthenticationController, :code
      post "/phone", AuthenticationController, :phone
      post "/reset", AuthenticationController, :reset
    end

    scope "/ads" do
      get "/", AdController, :list
      post "/", AdController, :create
      get "/:uuid", AdController, :show
      put "/:uuid", AdController, :update
      delete "/:uuid", AdController, :delete
    end 

    scope "/account" do
      get "/ads", AccountController, :ads
      put "/", AccountController, :information
      put "/password", AccountController, :password
    end

    scope "/upload" do
      post "/", UploadController, :upload
      delete "/", UploadController, :remove
    end

    get "/categories", MiscellaneousController, :categories
    get "/locations", MiscellaneousController, :locations

    get "/:phone/shop", AccountController, :shop
  end
end

apps/commercefacile_web/lib/commercefacile_web/views/layout_view.ex
defmodule Commercefacile.Web.LayoutView do
  use Commercefacile.Web, :view

  def active_if_current(conn, [{:to, to}, {:controller, controller}, {:action, action}])
  when is_list(action)
  do
    active = 
      action
      |> Enum.map(fn(action) -> {controller, action} end)
    with true <- active_path?(conn, to: to, active: active) do
      "is-active"
    end
  end
  def active_if_current(conn, [{:to, to}, {:controller, controller}, {:action, action}]) do
    with true <- active_path?(conn, to: to, active: [{controller, action}]) do
      "is-active"
    end
  end
end

apps/commercefacile_web/lib/commercefacile_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="Vendez, achetez, louez et proposez vos services sur le plus grand site de petites annonces gratuites au Togo : immobilier, voiture, moto, etc.">
    <meta name="author" content="@thomasdolar">

    <meta name="theme-color" content="#1d305d" />
    <meta name="msapplication-navbutton-color" content="#1d305d" />
    <meta name="apple-mobile-web-app-capable" content="yes" />  
    <meta name="apple-mobile-web-app-status-bar-style" content="#1d305d" />

    <meta property="fb:app_id" content="173791383126653"/>
    <meta name="twitter:site" content="@commercefacile">

    <%= render_existing @view_module, "meta." <> @view_template, assigns %>

    <%= render_existing @view_module, "title." <> @view_template, assigns %>

    <title>Commercefacile.com</title>
    
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/vendors/bulma.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style type="text/css">

      body{
        display: flex;
        min-height: 100vh;
        flex-direction: column;
      }

      .is-fixed-top{
        position: fixed;
        right: 0;
        left: 0;
        z-index: 1030;
      }

      a.nav-item{
        color: white;
        transition: all .5s;
      }

      .nav-menu a.nav-item{
        color: #77829d;
      }

      a.nav-item:hover{
        color: #77829d;
        border-bottom-color: #77829d !important;
      }

      a.nav-item.is-tab.is-active, a.nav-item.is-tab.is-active:hover{
        color: #1D305D;
        border-bottom-color: #1D305D !important;
        cursor: default;
      }

      .nav-toggle:hover{
        background-color: inherit;
      }

      .nav-toggle.is-active{
        background-color: #1D305D;
      }
      .nav-toggle.is-active span{
        background-color: #F79520;
      }

      .footer .menu-label{
          color: #4a597d;
      }

      .footer .menu-list a{
          color: #1D305D;
          transition: all .5s;
      }
      .footer .menu-list a:hover{
          color: #F79520;
          background-color: transparent;
      }
    </style>
    <%= render_existing @view_module, "styles." <> @view_template, assigns %>
  </head>

  <body>

        <!--start nav bar-->
    <nav class="nav is-fixed-top" style="background: #F79520;">
      <div class="container">
        <div class="nav-left">
          <a href="<%= page_path(@conn, :index) %>" class="nav-item">
            <img src="<%= static_path(@conn, "/images/logos/logo_w_d_white.png") %>" alt="Commercefacile.com logo">
          </a>
        </div>
        <div class="nav-center">
          <a href="<%= page_path(@conn, :index) %>" 
              class="nav-item is-tab is-hidden-mobile <%= active_if_current(@conn, to: page_path(@conn, :index), controller: Commercefacile.Web.PageController, action: :index) %>">
            Acceuil
          </a>
          <a href="<%= ad_path(@conn, :create) %>" 
            class="nav-item is-tab is-hidden-mobile <%= active_if_current(@conn, to: ad_path(@conn, :create), controller: Commercefacile.Web.AdController, action: :create) %>">
            Déposer une annonce</a>
          <a href="<%= ad_path(@conn, :index) %>" 
            class="nav-item is-tab is-hidden-mobile <%= active_if_current(@conn, to: ad_path(@conn, :index), controller: Commercefacile.Web.AdController, action: [:index, :show]) %>">
            Annonces</a>
        </div>
        <span class="nav-toggle">
          <span></span>
          <span></span>
          <span></span>
        </span>
        <div class="nav-right nav-menu">
          <a href="<%= page_path(@conn, :index) %>" 
            class="nav-item is-tab is-hidden-tablet <%= active_if_current(@conn, to: page_path(@conn, :index), controller: Commercefacile.Web.PageController, action: :index) %>">
            Acceuil</a>
          <a href="<%= ad_path(@conn, :create) %>" 
            class="nav-item is-tab is-hidden-tablet <%= active_if_current(@conn, to: ad_path(@conn, :create), controller: Commercefacile.Web.AdController, action: :create) %>">
            Déposer une Annonce</a>
          <a href="<%= ad_path(@conn, :index) %>" 
            class="nav-item is-tab is-hidden-tablet <%= active_if_current(@conn, to: ad_path(@conn, :index), controller: Commercefacile.Web.AdController, action: [:index, :show]) %>">
            Annonces</a>
          <% user = Guardian.Plug.current_resource(@conn) %>
          <%= unless user do %>
            <a href="<%= auth_path @conn, :get_login %>" class="nav-item is-tab">
              <figure class="image is-16x16" style="margin-right: 8px;">
                <img src="<%= static_path(@conn, "/images/icons/user.png") %>">
              </figure>
              Se connecter
            </a>            
          <% else %>
            <a href="<%= user_path(@conn, :dashboard, user.phone) %>" class="nav-item is-tab">
              <figure class="image is-16x16" style="margin-right: 8px;">
                <img src="<%= static_path(@conn, "/images/icons/user.png") %>">
              </figure>
              Mon Compte
            </a>
            <a href="" class="nav-item is-tab">
              <form action="<%= auth_path(@conn, :logout) %>" method="post">
                <input type="hidden" name="_csrf_token" value="<%= Plug.CSRFProtection.get_csrf_token() %>">
                <button type="submit" class="button is-link">Log out</button>
              </form>
            </a>
          <% end %>
        </div>
      </div>
    </nav>
    <!--end nav bar-->

  <!--start outer section-->
  <div style="padding-top: 70px; flex: 1;">
    <!--start main content-->
    <%= render @view_module, @view_template, assigns %>
    <!--end main content-->
  </div>
  <!--end outer section-->

      <!--start footer-->
    <footer class="footer" style="background: #f8f8f9; border-top: 3px solid #1D305D;">
      <div class="container">
        <div class="columns">
          <div class="column has-text-centered">
            <p class="menu-label">
              Transactions
            </p>
            <ul class="menu-list">
              <li><a>Payments</a></li>
              <li><a>Transfers</a></li>
              <li><a>Balance</a></li>
            </ul>
          </div>
          <div class="column has-text-centered">
            <p class="menu-label">
              Transactions
            </p>
            <ul class="menu-list">
              <li><a>Payments</a></li>
              <li><a>Transfers</a></li>
              <li><a>Balance</a></li>
            </ul>
          </div>
          <div class="column has-text-centered">
            <p class="menu-label">
              Transactions
            </p>
            <ul class="menu-list">
              <li><a>Payments</a></li>
              <li><a>Transfers</a></li>
              <li><a>Balance</a></li>
            </ul>
          </div>
          <div class="column has-text-centered">
            <p class="menu-label">
              Transactions
            </p>
            <ul class="menu-list">
              <li><a>Payments</a></li>
              <li><a>Transfers</a></li>
              <li><a>Balance</a></li>
            </ul>
          </div>
        </div>
        <hr>
        <div class="content has-text-centered">
          <figure class="image is-32x32" style="display: inline-block;">
            <img src="<%= static_path(@conn, "/images/logos/logo_acro.png") %>">
          </figure>
          <p>
            Commercefacile.com
          </p>
        </div>
      </div>
    </footer>
    <!--end footer-->

    <script type="text/javascript">
      var contains = function(el, className){
          var c = false;
          if (el.classList)
              c = el.classList.contains(className);
          else
              c = new RegExp('(^| )' + className + '( |$)', 'gi').test(el.className);
          
          return c;
      };
      var addClassName = function(el, className){
          if (el.classList)
              el.classList.add(className);
          else
              el.className += ' ' + className;
      };

      var removeClassName = function(el, className){
          if (el.classList)
              el.classList.remove(className);
          else
              el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
      }

      var menuToggle = document.querySelector('.nav-toggle'),
              menu = document.querySelector('.nav-menu');

          menuToggle.addEventListener('click', function(e){
              if(contains(menu, "is-active")){
                  removeClassName(menu, "is-active");
                  removeClassName(menuToggle, "is-active");
              }else{
                  addClassName(menu, "is-active");
                  addClassName(menuToggle, "is-active");
              }
          })
    </script>

 <%= render_existing @view_module, "scripts." <> @view_template, assigns %>

  </body>
</html>